Update ESP8266 FQBN in .travis.yml
Some of the menu IDs for the ESP8266 boards were recently changed, which causes compilation to fail:

Error: CpuFrequency: Invalid option for board "d1_mini"